CREATE DATABASE IF NOT EXISTS REGISTRO_VEHICULOS;
USE REGISTRO_VEHICULOS;

CREATE TABLE PROPIETARIOS (
    IdPropietario INT AUTO_INCREMENT PRIMARY KEY,
    Nombre        VARCHAR(80) NOT NULL,
    Cedula        VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE VEHICULOS (
    IdVehiculo    INT AUTO_INCREMENT PRIMARY KEY,
    Placa         VARCHAR(15) NOT NULL UNIQUE,
    Marca         VARCHAR(40) NOT NULL,
    Modelo        VARCHAR(40) NOT NULL,
    Anio          INT NOT NULL,
    IdPropietario INT NOT NULL,
    CONSTRAINT FK_VEHICULOS_PROPIETARIOS FOREIGN KEY (IdPropietario) REFERENCES PROPIETARIOS (IdPropietario)
);

INSERT INTO PROPIETARIOS (Nombre, Cedula) VALUES
('Ricardo Monge', '109870222'), ('Paola Salazar', '207650333');

INSERT INTO VEHICULOS (Placa, Marca, Modelo, Anio, IdPropietario) VALUES
('BCD123', 'Toyota', 'Corolla', 2020, 1),
('XYZ789', 'Honda', 'CR-V', 2022, 2);
